version: '3'
services:
  db:
    image: 'postgres:15.3'
    restart: always
    environment:
      POSTGRES_DB: subs
      POSTGRES_USER: subs
      POSTGRES_PASSWORD: subs
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    labels:
      io.portainer.accesscontrol.public: ""
volumes:
  db-data:
    labels:
      io.portainer.accesscontrol.public: ""